version: "3.8"
services:
  db:
    image: mongo:latest
    volumes:
      - data:/data/db
    ports:
      - "27017:27017"
  backend:
    build: ./server
    ports:
      - "8080:8080"
    volumes:
      - logs:/app/logs
      - ./server:/app
      - /app/node_modules
    depends_on:
      - db
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
    stdin_open: true
    tty: true
    depends_on:
      - backend

volumes:
  data:
  logs: